# Default values for DirectorOnPrem.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Update platfrom according to your Platform, Default include(GKE,Packet) and SUSE
platform: Default

server:
  release: 1.7.0-ee
  dockerSecret: directoronprem-registry-secret
  protocol: http
  url:
  httpNodePort: 30380
  httpsNodePort: 30381
  apiAuthAccessMode: unrestricted
  serverDefaultAccessGrant: true
  apiUiEnabled: true
  maxMemberCountInOneProject: 10
  setupName: directoronprem
  apiAuthExternalProviderEnabled: false
  apiAuthExternalProviderConfigured:
  apiAuthInternalProviderEnabled: true
  apiAuthInternalProviderConfigured: localAuthConfig
  apiAuthGithubClientId:
  apiAuthGithubClientSecret:
  apiAuthGoogleClientId:
  apiAuthGoogleClientSecret:
  clusterDomain: cluster.local
  featureSubscriptionDisable: false
  subscriptionType: internal
  featureBillingDisable: true
  billingType: external
  featureEmailDisable: true
  senderEmailAddress:
  senderEmailPassword:
  featureDocsDisable: false
  docsUrl: https://help.mayadata.io/hc/en-us
  featureChatBotDisable: true
  slackConfigBotClientId:
  slackConfigBotClientSecret:
  slackNotificationWelcomeMessage:
  featureKialiDisable: true
  analyticsGoogleCode:
  autoconnectLocalCluster: true
  # The host URL of the AD server
  adHost:
  # The base domain of the AD server
  adDomain:
  # The port number on which the AD server is listening
  adPort: 636
  adTLS: true
  # an ADuser with read access to the AD server, someuser@domain.d1adSvcAccUser:
  adSvcAccUser:
  adSvcAccPwd:
  adNameField: givenName
  # default objectclass for users
  adUserObjectClass: person
  adGroupObjectClass: group
  # connection timeout in milliseconds
  adConnectionTimeout: 5000

mysql:
  #storageClass: openebs-jiva-default
  storageClass: standard
  storageCapacity: 50Gi

elasticSearch:
  #storageClass: openebs-hostpath
  storageClass: standard
  storageCapacity: 50Gi
  replicas: 1

cassandra:
  #storageClass: openebs-hostpath
  storageClass: standard
  storageCapacity: 50Gi
  replicas: 1

mayaStore:
  #storageClass: cstor-storage-class
  storageClass: standard
  storageCapacity: 10Gi

grafana:
  #storageClass: cstor-storage-class
  storageClass: standard
  storageCapacity: 50Gi

cortex:
  replicationFactor: 1
  timeout: 5s

alertStore:
  replicationFactor: 1

ingester:
  replicas: 1

querier:
  replicas: 1

curator:
  retentionPeriod: 30
## doc/charts/nginx/index.md
## doc/architecture/decisions.md#nginx-ingress
## Installation & configuration of charts/nginx-ingress
nginx-ingress:
  enabled: true
  tcpExternalConfig: "true"
  controller:
    kind: DaemonSet
    config:
      hsts-include-subdomains: "false"
      server-name-hash-bucket-size: "256"
      enable-vts-status: "true"
      use-http2: "false"
      ssl-ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
      ssl-protocols: "TLSv1.3 TLSv1.2"
      server-tokens: "false"
    extraArgs:
      force-namespace-isolation: ""
    service:
      enabled: false
      type: NodePort
      nodePorts:
        http: 30380
        https: 30381
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    publishService:
      enabled: true
    replicaCount: 1
    minAvailable: 1
    scope:
      enabled: true
    stats:
      enabled: true
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
  defaultBackend:
    minAvailable: 1
    replicaCount: 2
    resources:
      requests:
        cpu: 5m
        memory: 5Mi
  rbac:
    create: true
  serviceAccount:
    create: true

