apiVersion: v1
name: nginx-ingress
version: 1.29.3
appVersion: 0.27.1
home: https://github.com/kubernetes/ingress-nginx
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
maintainers:
- name: MayaData
  email: support@mayadata.com
name: nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
- https://github.com/mayadata-io/director-charts/charts/nginx-ingress/
engine: gotpl
kubeVersion: ">=1.10.0-0"
